#
# © oMeN23
# 
#!/bin/bash

# IMPORTANT: THIS IS MENT TO RUN AS AN HOURLY CRON.JOB
# RIP LIVESTREAMS USING YOUTUBE'S v3 API AND STREAMLINK
# AND POST UPDATES TO DISCORD CHANNELS (DISCORD BOT TAKES LINK AS argv[2])
# © 2018–2019 oMeN23 
# NOT GPL - NOT LGPL - this is my IP.
